routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

//->middleware('auth');


Route::middleware(['auth'])->group(function () {

    Route::resource('companias', 'CompaniesController');

    Route::get('projects/create/{company_id?}', 'ProjectsController@create');
    Route::post('/projects/adduser', 'ProjectsController@adduser')->name('projects.adduser');
    Route::resource('projects', 'ProjectsController');
    
    Route::resource('roles', 'RolesController');
   
    Route::resource('tareas', 'TareasControlador');
    Route::resource('users', 'UsersController');
    Route::resource('comments', 'CommentsController');


    Route::resource('pbis', 'PbisController');
    Route::resource('sprints', 'SprintsControlador');

    Route::get('pbis/edit/{id}', 'PbisController@edit')->name('pbis.edit');
    Route::get('pbis/update', 'PbisController@update')->name('pbis.update');
    Route::get('/pbis/delete/{id}', 'PbisController@destroy')->name('pbis.delete');

    Route::get('sprints', 'SprintsControlador@store');
    Route::post('/sprints/create', 'SprintsControlador@create');
    Route::get('/sprints/delete/{id}', 'SprintsControlador@destroy')->name('sprints.delete');
    Route::get('sprints/edit/{id}', 'SprintsControlador@edit')->name('sprints.edit');
    Route::post('/sprints/update', 'SprintsControlador@update')->name('sprints.update');
    //Route::get('sprints/create', 'ProjectsController@createSprint');
    //Route::get('pbis/create', 'PbisController@store')->name('pbis.store');
});

app/Sprint.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Sprint extends Model
{
    protected $fillable = [
        'id',
        'nombre',
        'description',
        'project_id'

    ];

    public function project(){
        return $this->belongsTo('App\Project');
    }

    public function pbis()
    {
    	return $this->hasMany('App\Pbi');
    }
}

resources/views/sprints/create.blade.php
@extends('layouts.app')

@section('content')



     
     <div class="row col-md-9 col-lg-9 col-sm-9 pull-left " style="background: white;">
    <h1>Crear Sprint </h1>

      <!-- Example row of columns -->
      <div class="row  col-md-12 col-lg-12 col-sm-12" >

      <form method="post" action="{{ route('sprints.create') }}">
                            {{ csrf_field() }}

                            <input   
                            class="form-control"
                            type="hidden"
                                    name="idproject"
                                    dd($wow);
                                    value="{{ $wow }}"
                                     />
                            </div>

                            <div class="form-group">
                                <label for="company-name">Nombre<span class="required">*</span></label>
                                <input   placeholder="Nombre del sprint"  
                                          id="company-name"
                                          required
                                          name="name"
                                          spellcheck="false"
                                          class="form-control"
                                           />
                            </div>


                            <div class="form-group">
                                <label for="company-content">Descripcion</label>
                                <textarea placeholder="Descripcion del sprint" 
                                          style="resize: vertical" 
                                          id="company-content"
                                          name="description"
                                          rows="5" spellcheck="false"
                                          class="form-control autosize-target text-left">
                                </textarea>
                            </div>
                            <div class="form-group">
                                <input type="submit" class="btn btn-primary"
                                       value="Crear"/>
                            </div>
                        </form>
   

      </div>
</div>


<div class="col-sm-3 col-md-3 col-lg-3 pull-right">
          <!--<div class="sidebar-module sidebar-module-inset">
            <h4>About</h4>
            <p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
          </div> -->
          <div class="sidebar-module">
            <h4>Actions</h4>
            <ol class="list-unstyled">
              <li><a href="/companies"> <i class="fa fa-building-o" aria-hidden="true"></i> My sprints</a></li>
              
            </ol>
          </div>

          <!--<div class="sidebar-module">
            <h4>Members</h4>
            <ol class="list-unstyled">
              <li><a href="#">March 2014</a></li>
            </ol>
          </div> -->
        </div>


    @endsection

resources/views/sprints/edit.blade.php
@extends('layouts.app')

@section('content')



<div class="row col-md-9 col-lg-9 col-sm-9 pull-left " style="background: white;">
<h1>Actualizar datos del sprint  {{ $project->nombre }} </h1>

      <!-- Example row of columns -->
      <div class="row  col-md-12 col-lg-12 col-sm-12" >

                                 
      <form method="post" action="{{ route('sprints.update') }}">
                            {{ csrf_field() }}

                            <input type="hidden" name="sprint_id" value="{{ $project->id }}">
                           {{-- <input type="hidden" name="sprint_id" value="{{ $project->id }}"> --}}
                            <input type="hidden" name="_method" value="put">


                            <div class="form-group">
                                <label for="company-name">Nombre<span class="required"></span></label>
                                <input   placeholder="Enter name"  
                                          id="proyecto-name"
                                          required
                                          name="name"
                                          spellcheck="false"
                                          class="form-control"
                                          value="{{ $project->nombre }}"
                                           />
                            </div>


                            <div class="form-group">
                                <input type="submit" class="btn btn-primary"
                                       value="Submit"/>
                            </div>
                        </form>
   

      </div>
</div>


        <div class="col-sm-3 col-md-3 col-lg-3 pull-right">
          
          <div class="sidebar-module">
            <h4>Actions</h4>
            <ol class="list-unstyled">
              <li><a href="/projects/{{ $project->id }}"><i class="fa fa-building-o" 
                aria-hidden="true"></i> Ver sprints</a></li>
              <li><a href="/projects"><i class="fa fa-building" 
                aria-hidden="true"></i> Proyectos</a></li>
              
            </ol>
          </div>

        </div>


    @endsection

resources/views/sprints/show.blade.php
@extends('layouts.app')

@section('content')
 {{--
<h1>Project Task List for:  "{{ $p_name->project_name }}" </h1>
    <table class="table table-striped">
        <thead>
        <tr>
            <th>Task Title</th>
            <th>Project Name</th>
            <th>Priority</th>
            <th>Status</th>
            <th>Actions</th>
        </tr>
        </thead>

             @if ( !$task_list->isEmpty() ) 
        <tbody>
            @foreach ( $task_list as $task)
            <tr>
                <td>{{ $task->task_title }} </td>
        </tbody>
       
        
    </table>

 ---}}
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title">
                <span class="glyphicon glyphicon-comment"></span> 
                 <b> Historias de usuario </b>
              
                 <a href="{{ route('pbis.create', ['idsprint' => $idsprint->id]) }}" 
                        class="pull-right btn btn-primary btn-sm">
                        <span 
                        class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Crear nuevo 
                      </a> 
                    
             </h3>
            
        </div> 

        <div class="panel-body">
            
            <ul class="list-group">
                @foreach($pbis as $pbi)
                    <li class="list-group-item"> 
                        <i class="fa fa-play" aria-hidden="true"></i>
                        
                        <a href="/pbis/{{ $pbi->id }}" > {{ $pbi->titulo }}</a>     
                                
                        <a href="/pbis/edit/{{ $pbi->id }}" 
                            class="pull-right btn btn-primary btn-sm">
                            <span 
                            class="glyphicon glyphicon-pencil" aria-hidden="true"></span> 
                          </a> 

                          <a href="/pbis/delete/{{ $pbi->id }}" 
                            class="pull-right btn btn-danger btn-sm">
                            <span 
                            class="glyphicon glyphicon-trash" aria-hidden="true"></span> 
                          </a> 
                    </li>
                @endforeach
            </ul>
        </div>

    </div>

    

@endsection