routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

//->middleware('auth');


Route::middleware(['auth'])->group(function () {

    Route::resource('companias', 'CompaniesController');

    Route::get('projects/create/{company_id?}', 'ProjectsController@create');
    Route::post('/projects/adduser', 'ProjectsController@adduser')->name('projects.adduser');
    Route::resource('projects', 'ProjectsController');
    
    Route::resource('roles', 'RolesController');
   
    Route::resource('tareas', 'TareasControlador');
    Route::resource('users', 'UsersController');
    Route::resource('comments', 'CommentsController');


    Route::resource('pbis', 'PbisController');
    Route::resource('sprints', 'SprintsControlador');

    Route::get('pbis/edit/{id}', 'PbisController@edit')->name('pbis.edit');
    Route::get('pbis/update', 'PbisController@update')->name('pbis.update');
    Route::get('/pbis/delete/{id}', 'PbisController@destroy')->name('pbis.delete');

    Route::get('sprints', 'SprintsControlador@store');
    Route::post('/sprints/create', 'SprintsControlador@create');
    Route::get('/sprints/delete/{id}', 'SprintsControlador@destroy')->name('sprints.delete');
    Route::get('sprints/edit/{id}', 'SprintsControlador@edit')->name('sprints.edit');
    Route::post('/sprints/update', 'SprintsControlador@update')->name('sprints.update');
    //Route::get('sprints/create', 'ProjectsController@createSprint');
    //Route::get('pbis/create', 'PbisController@store')->name('pbis.store');
});

resources/views/companias/create.blade.php
@extends('layouts.app')

@section('content')



     
     <div class="row col-md-9 col-lg-9 col-sm-9 pull-left " style="background: white;">
    <h1>Crear nueva compañia </h1>

      <!-- Example row of columns -->
      <div class="row  col-md-12 col-lg-12 col-sm-12" >

      <form method="post" action="{{ route('companias.store') }}">
                            {{ csrf_field() }}


                            <div class="form-group">
                                <label for="company-name">Nombre<span class="required">*</span></label>
                                <input   placeholder="Nombre de su compañia"  
                                          id="company-name"
                                          required
                                          name="name"
                                          spellcheck="false"
                                          class="form-control"
                                           />
                            </div>


                            <div class="form-group">
                                <label for="company-content">Descripcion</label>
                                <textarea placeholder="Descripcion de su compañia" 
                                          style="resize: vertical" 
                                          id="company-content"
                                          name="description"
                                          rows="5" spellcheck="false"
                                          class="form-control autosize-target text-left">

                                          
                                          </textarea>
                            </div>
                            <div class="form-group">
                                <input type="submit" class="btn btn-primary"
                                       value="Crear"/>
                            </div>
                        </form>
   

      </div>
</div>


<div class="col-sm-3 col-md-3 col-lg-3 pull-right">
          <!--<div class="sidebar-module sidebar-module-inset">
            <h4>About</h4>
            <p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
          </div> -->
          <div class="sidebar-module">
            <h4>Opciones</h4>
            <ol class="list-unstyled">
              <li><a href="/companias"> <i class="fa fa-building-o" aria-hidden="true"></i> Mis compañias</a></li>
              
            </ol>
          </div>

          <!--<div class="sidebar-module">
            <h4>Members</h4>
            <ol class="list-unstyled">
              <li><a href="#">March 2014</a></li>
            </ol>
          </div> -->
        </div>


    @endsection

resources/views/companias/edit.blade.php
@extends('layouts.app')

@section('content')



<div class="row col-md-9 col-lg-9 col-sm-9 pull-left " style="background: white;">
  <h1> Actualizar compañia </h1>

      <!-- Example row of columns -->
      <div class="row  col-md-12 col-lg-12 col-sm-12" >

      <form method="post" action="{{ route('companias.update',[$company->id]) }}">
                            {{ csrf_field() }}

                            <input type="hidden" name="_method" value="put">
                            <input type="hidden" name="id_compania" value="{{ $company->id }}">

                            <div class="form-group">
                                <label for="company-name">Nombre<span class="required">*</span></label>
                                <input   placeholder="Enter name"  
                                          id="company-name"
                                          required
                                          name="name"
                                          spellcheck="false"
                                          class="form-control"
                                          value="{{ $company->name }}"
                                           />
                            </div>


                            <div class="form-group">
                                <label for="company-content">Descripcion</label>
                                <textarea placeholder="Enter description" 
                                          style="resize: vertical" 
                                          id="company-content"
                                          name="description"
                                          rows="5" spellcheck="false"
                                          class="form-control autosize-target text-left">
                                          {{ $company->description }}</textarea>
                            </div>
                            <div class="form-group">
                                <input type="submit" class="btn btn-primary"
                                       value="Actualizar"/>
                            </div>
                        </form>
   

      </div>
</div>


        <div class="col-sm-3 col-md-3 col-lg-3 pull-right">
          
          <div class="sidebar-module">
            <h4>Opciones</h4>
              <ol class="list-unstyled">
                <li><a href="/companias/{{ $company->id }}"><i 
                  class="fa fa-building-o" aria-hidden="true"></i>
                Ver compañias</a></li>
                <li><a href="/companias"><i class="fa fa-building" 
                  aria-hidden="true"></i> Todas las compañias </a></li>
                
              </ol>
          </div>
        </div>
    @endsection

resources/views/companias/index.blade.php
@extends('layouts.app')

@section('content')

<div class="col-md-6 col-lg-6 col-md-offset-3  col-lg-offset-3">
    <div class="panel panel-primary ">
        <div class="panel-heading">Compañias 
            <a class="pull-right btn btn-primary btn-sm" href="/companias/create">
            <i class="fa fa-plus-square" aria-hidden="true"></i>  Crear nueva</a> 
        </div>

        <div class="panel-body">
            <ul class="list-group">
                @foreach($companies as $company)
                    <li class="list-group-item"> 
                        <i class="fa fa-play" aria-hidden="true"></i> 
                        <a href="/companias/{{ $company->id }}" >  {{ $company->name }}</a>
                    </li>
                @endforeach
            </ul>
        </div>
    </div>
</div>

@endsection

resources/views/companias/show.blade.php
@extends('layouts.app')

@section('content')


     
     <div class="row col-md-9 col-lg-9 col-sm-9 pull-left ">
      <!-- The justified navigation menu is meant for single line per list item.
           Multiple lines will require custom code not provided by Bootstrap. -->
      <!-- Jumbotron -->
        <div class="jumbotron" >
          <h1>{{ $company->name }}</h1>
          <p class="lead">{{ $company->description }}</p>
        </div>

        <!-- Example row of columns -->
        <div class="row  col-md-12 col-lg-12 col-sm-12" style="background: white; margin: 10px; ">
          <a href="/projects/create/{{ $company->id }}" 
            class="pull-right btn btn-default btn-sm" > Nuevo proyecto
          </a>
          @foreach($company->projects as $project)
            <div class="col-lg-4 col-md-4 col-sm-4">
                <h2> <b> {{ $project->name }} </b> </h2>
                <p class="text-danger"> {{$project->description}} </p>
                <p><a class="btn btn-primary" href="/projects/{{ $project->id }}" 
                  role="button"> ver <b> {{ $project->name }} </b> </a></p>
            </div>
          @endforeach
        </div>
    </div>


<div class="col-sm-3 col-md-3 col-lg-3 pull-right">
         
          <div class="sidebar-module">
            <h4>Actions</h4>
            <ol class="list-unstyled">
              <li><a href="/companias/{{ $company->id }}/edit">Editar</a></li>
              <li><a href="/projects/create/{{ $company->id }}">Añadir proyecto</a></li>
              <li><a href="/companias">Mis compañias</a></li>
              <li><a href="/companias/create">Crear compañia</a></li>
            
             <br/>
            
            
              <li>
              <a   
              href="#"
                  onclick="
                  var result = confirm('Estas seguro de eliminar esta compañia?');
                      if( result ){
                              event.preventDefault();
                              document.getElementById('delete-form').submit();
                      }
                          "
                          >
                  Eliminar
              </a>

              <form id="delete-form" action="{{ route('companias.destroy',[$company->id]) }}" 
                method="POST" style="display: none;">
                        <input type="hidden" name="_method" value="delete">
                        {{ csrf_field() }}
              </form>

              </li>
            </ol>
          </div>

        </div>


    @endsection